Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.hostname = "ansibleui"
    config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"
    config.vm.network "private_network", ip: "192.168.200.10"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4192"
        vb.cpus = "4"
    end
end